version: '3.5'

services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres-container
    hostname: ${DATABASE_HOST}
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USERNAME: ${DATABASE_USERNAME}
    volumes:
      - ./data/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./db:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    ports:
      - '127.0.0.1:3000:8080'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

volumes:
  db: 

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   container_name: nest-pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=pgadmin4
  #   ports:
  #     - '5050:80'
  #   depends_on:
  #     - db
